### ISSUE TITLE
우분투 12.04 에서 apt install 로 설치 시 오류

### ISSUE THREAD

**Issue by freeNanum** [hamonikr/hamonikr-nemo-rabbitvcs#3]
우분투 12.04 에서 apt install 로 설치 시 오류가 납니다.

curl -sL https://pkg.hamonikr.org/add-hamonikr.apt | sudo -E bash -

위 명령은 잘 수행되나,
 다음 명령을 실행하면,
sudo apt install -y hamonikr-nemo-rabbitvcs

하기 첨부 이미지와 같은 에러가 납니다.

![nemo-rabbitvcs-err#1](https://user-images.githubusercontent.com/55156081/118403980-f752e580-b6ab-11eb-853a-0437e74907d4.png)

**Comment by chaeya** [comment]
현재 패키지된 버전이 우분투 12.04를 지원하고 있지 않습니다.
Ubuntu 18.04 이상의 저장소만 지원하고 있는 상황이라 설치하신 버전은 패키지가 없는 상태입니다.
