### ISSUE TITLE
우분투 20.04 에서 apt install 로 설치 시 오류

### ISSUE THREAD

**Issue by freeNanum** [hamonikr/hamonikr-nemo-rabbitvcs#6]
우분투 20.04 에서 apt install 로 설치 시 오류가 납니다.

curl -sL https://pkg.hamonikr.org/add-hamonikr.apt | sudo -E bash -

위 명령은 잘 수행되나,
다음 명령을 실행하면,
sudo apt install -y hamonikr-nemo-rabbitvcs

하기 첨부 이미지와 같은 에러가 납니다.
![nemo-rabbitvcs-err#1](https://user-images.githubusercontent.com/55156081/120111088-7ca9c000-c1ab-11eb-9a15-262cb2cab135.png)

참고로 커널 버전은 하기와 같습니다.
`uname -a
Linux ZEUS 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by chaeya** [comment]
새 릴리즈가 저장소에 업데이트 되었습니다.
터미널에서 다음과 같이 실행해보세요.
```bash
sudo apt update
sudo apt install -y hamonikr-nemo-rabbitvcs
```
